/********************************************************************************
** Form generated from reading UI file 'gamewindow.ui'
**
** Created by: Qt User Interface Compiler version 5.14.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_GAMEWINDOW_H
#define UI_GAMEWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_GameWindow
{
public:
    QWidget *centralWidget;
    QGraphicsView *graphicsView;
    QPushButton *endTurnButton;
    QPushButton *buildButton;
    QLabel *Wood1;
    QLabel *Ore1;
    QLabel *Sheep1;
    QLabel *Brick1;
    QLabel *Wheat1;
    QLabel *Brick2;
    QLabel *Wood2;
    QLabel *Wheat2;
    QLabel *Ore2;
    QLabel *Sheep2;
    QLabel *Brick3;
    QLabel *Sheep3;
    QLabel *Wheat3;
    QLabel *Ore3;
    QLabel *Wood3;
    QLabel *Ore4;
    QLabel *Sheep4;
    QLabel *Wheat4;
    QLabel *Wood4;
    QLabel *Brick4;
    QPushButton *findOrderButton;
    QLabel *label;
    QLineEdit *numPlayers;
    QLabel *TextBox;
    QLabel *p1d1;
    QLabel *p1d2;
    QLabel *p4d1;
    QLabel *p4d2;
    QLabel *p3d1;
    QLabel *p3d2;
    QLabel *p2d2;
    QLabel *p2d1;
    QLabel *label_2;
    QPushButton *brickButton;
    QPushButton *oreButton;
    QPushButton *sheepButton;
    QPushButton *wheatButton;
    QPushButton *woodButton;
    QLabel *label_3;
    QPushButton *settlementButton;
    QPushButton *cityButton;
    QPushButton *roadButton;
    QPushButton *tradeButton;
    QPushButton *undoButton;
    QPushButton *developButton;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *KnightLabel;
    QLabel *brickLabel;
    QLabel *oreLabel;
    QLabel *sheepLabel;
    QLabel *wheatLabel;
    QLabel *woodLabel;
    QLabel *label_6;
    QLabel *settleLabel;
    QLabel *roadLabel;
    QLabel *cityLabel;
    QLabel *developLabel;
    QPushButton *Player4Button;
    QPushButton *Player1Button;
    QPushButton *Player3Button;
    QPushButton *Player2Button;
    QLabel *label_7;
    QLabel *RoadLabel;
    QLabel *label_8;
    QGraphicsView *tradeView;
    QLabel *Player1Trade;
    QLabel *Player2Trade;
    QLabel *brickTrade;
    QLabel *woodTrade;
    QLabel *oreTrade;
    QLabel *sheepTrade;
    QLabel *wheatTrade;
    QLabel *brick2Trade;
    QLabel *ore2Trade;
    QLabel *wheat2Trade;
    QLabel *sheep2Trade;
    QLabel *wood2Trade;
    QLineEdit *oreIn;
    QLineEdit *brickIn;
    QLineEdit *sheepIn;
    QLineEdit *wheatIn;
    QLineEdit *woodIn;
    QLineEdit *woodOut;
    QLineEdit *oreOut;
    QLineEdit *wheatOut;
    QLineEdit *sheepOut;
    QLineEdit *brickOut;
    QLabel *forLabel;
    QPushButton *acceptButton;
    QPushButton *denyButton;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *GameWindow)
    {
        if (GameWindow->objectName().isEmpty())
            GameWindow->setObjectName(QString::fromUtf8("GameWindow"));
        GameWindow->resize(923, 755);
        centralWidget = new QWidget(GameWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        graphicsView = new QGraphicsView(centralWidget);
        graphicsView->setObjectName(QString::fromUtf8("graphicsView"));
        graphicsView->setGeometry(QRect(20, 0, 741, 651));
        endTurnButton = new QPushButton(centralWidget);
        endTurnButton->setObjectName(QString::fromUtf8("endTurnButton"));
        endTurnButton->setGeometry(QRect(550, 660, 121, 51));
        buildButton = new QPushButton(centralWidget);
        buildButton->setObjectName(QString::fromUtf8("buildButton"));
        buildButton->setGeometry(QRect(430, 660, 121, 51));
        Wood1 = new QLabel(centralWidget);
        Wood1->setObjectName(QString::fromUtf8("Wood1"));
        Wood1->setGeometry(QRect(40, 100, 61, 16));
        Ore1 = new QLabel(centralWidget);
        Ore1->setObjectName(QString::fromUtf8("Ore1"));
        Ore1->setGeometry(QRect(40, 40, 55, 16));
        Sheep1 = new QLabel(centralWidget);
        Sheep1->setObjectName(QString::fromUtf8("Sheep1"));
        Sheep1->setGeometry(QRect(40, 60, 61, 16));
        Brick1 = new QLabel(centralWidget);
        Brick1->setObjectName(QString::fromUtf8("Brick1"));
        Brick1->setGeometry(QRect(40, 20, 55, 16));
        Wheat1 = new QLabel(centralWidget);
        Wheat1->setObjectName(QString::fromUtf8("Wheat1"));
        Wheat1->setGeometry(QRect(40, 80, 71, 16));
        Brick2 = new QLabel(centralWidget);
        Brick2->setObjectName(QString::fromUtf8("Brick2"));
        Brick2->setGeometry(QRect(40, 530, 55, 16));
        Wood2 = new QLabel(centralWidget);
        Wood2->setObjectName(QString::fromUtf8("Wood2"));
        Wood2->setGeometry(QRect(40, 610, 61, 16));
        Wheat2 = new QLabel(centralWidget);
        Wheat2->setObjectName(QString::fromUtf8("Wheat2"));
        Wheat2->setGeometry(QRect(40, 590, 61, 16));
        Ore2 = new QLabel(centralWidget);
        Ore2->setObjectName(QString::fromUtf8("Ore2"));
        Ore2->setGeometry(QRect(40, 550, 55, 16));
        Sheep2 = new QLabel(centralWidget);
        Sheep2->setObjectName(QString::fromUtf8("Sheep2"));
        Sheep2->setGeometry(QRect(40, 570, 61, 16));
        Brick3 = new QLabel(centralWidget);
        Brick3->setObjectName(QString::fromUtf8("Brick3"));
        Brick3->setGeometry(QRect(680, 530, 55, 16));
        Sheep3 = new QLabel(centralWidget);
        Sheep3->setObjectName(QString::fromUtf8("Sheep3"));
        Sheep3->setGeometry(QRect(680, 570, 71, 16));
        Wheat3 = new QLabel(centralWidget);
        Wheat3->setObjectName(QString::fromUtf8("Wheat3"));
        Wheat3->setGeometry(QRect(680, 590, 71, 16));
        Ore3 = new QLabel(centralWidget);
        Ore3->setObjectName(QString::fromUtf8("Ore3"));
        Ore3->setGeometry(QRect(680, 550, 55, 16));
        Wood3 = new QLabel(centralWidget);
        Wood3->setObjectName(QString::fromUtf8("Wood3"));
        Wood3->setGeometry(QRect(680, 610, 61, 16));
        Ore4 = new QLabel(centralWidget);
        Ore4->setObjectName(QString::fromUtf8("Ore4"));
        Ore4->setGeometry(QRect(690, 40, 55, 16));
        Sheep4 = new QLabel(centralWidget);
        Sheep4->setObjectName(QString::fromUtf8("Sheep4"));
        Sheep4->setGeometry(QRect(690, 60, 61, 16));
        Wheat4 = new QLabel(centralWidget);
        Wheat4->setObjectName(QString::fromUtf8("Wheat4"));
        Wheat4->setGeometry(QRect(690, 80, 61, 16));
        Wood4 = new QLabel(centralWidget);
        Wood4->setObjectName(QString::fromUtf8("Wood4"));
        Wood4->setGeometry(QRect(690, 100, 61, 16));
        Brick4 = new QLabel(centralWidget);
        Brick4->setObjectName(QString::fromUtf8("Brick4"));
        Brick4->setGeometry(QRect(690, 20, 55, 16));
        findOrderButton = new QPushButton(centralWidget);
        findOrderButton->setObjectName(QString::fromUtf8("findOrderButton"));
        findOrderButton->setGeometry(QRect(180, 260, 411, 101));
        QFont font;
        font.setPointSize(20);
        findOrderButton->setFont(font);
        findOrderButton->setIconSize(QSize(30, 30));
        findOrderButton->setAutoDefault(false);
        findOrderButton->setFlat(false);
        label = new QLabel(centralWidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(30, 670, 151, 16));
        numPlayers = new QLineEdit(centralWidget);
        numPlayers->setObjectName(QString::fromUtf8("numPlayers"));
        numPlayers->setGeometry(QRect(180, 670, 113, 22));
        TextBox = new QLabel(centralWidget);
        TextBox->setObjectName(QString::fromUtf8("TextBox"));
        TextBox->setGeometry(QRect(170, 10, 461, 41));
        p1d1 = new QLabel(centralWidget);
        p1d1->setObjectName(QString::fromUtf8("p1d1"));
        p1d1->setGeometry(QRect(110, 120, 30, 30));
        p1d1->setMinimumSize(QSize(30, 30));
        p1d1->setMaximumSize(QSize(30, 30));
        p1d2 = new QLabel(centralWidget);
        p1d2->setObjectName(QString::fromUtf8("p1d2"));
        p1d2->setGeometry(QRect(140, 120, 30, 30));
        p1d2->setMinimumSize(QSize(30, 30));
        p1d2->setMaximumSize(QSize(30, 30));
        p4d1 = new QLabel(centralWidget);
        p4d1->setObjectName(QString::fromUtf8("p4d1"));
        p4d1->setGeometry(QRect(615, 110, 30, 30));
        p4d1->setMinimumSize(QSize(30, 30));
        p4d1->setMaximumSize(QSize(30, 30));
        p4d2 = new QLabel(centralWidget);
        p4d2->setObjectName(QString::fromUtf8("p4d2"));
        p4d2->setGeometry(QRect(645, 110, 30, 30));
        p4d2->setMinimumSize(QSize(30, 30));
        p4d2->setMaximumSize(QSize(30, 30));
        p3d1 = new QLabel(centralWidget);
        p3d1->setObjectName(QString::fromUtf8("p3d1"));
        p3d1->setGeometry(QRect(615, 496, 30, 30));
        p3d1->setMinimumSize(QSize(30, 30));
        p3d1->setMaximumSize(QSize(30, 30));
        p3d2 = new QLabel(centralWidget);
        p3d2->setObjectName(QString::fromUtf8("p3d2"));
        p3d2->setGeometry(QRect(645, 496, 30, 30));
        p3d2->setMinimumSize(QSize(30, 30));
        p3d2->setMaximumSize(QSize(30, 30));
        p2d2 = new QLabel(centralWidget);
        p2d2->setObjectName(QString::fromUtf8("p2d2"));
        p2d2->setGeometry(QRect(140, 496, 30, 30));
        p2d2->setMinimumSize(QSize(30, 30));
        p2d2->setMaximumSize(QSize(30, 30));
        p2d1 = new QLabel(centralWidget);
        p2d1->setObjectName(QString::fromUtf8("p2d1"));
        p2d1->setGeometry(QRect(110, 496, 30, 30));
        p2d1->setMinimumSize(QSize(30, 30));
        p2d1->setMaximumSize(QSize(30, 30));
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(780, 20, 91, 16));
        brickButton = new QPushButton(centralWidget);
        brickButton->setObjectName(QString::fromUtf8("brickButton"));
        brickButton->setGeometry(QRect(810, 40, 81, 31));
        oreButton = new QPushButton(centralWidget);
        oreButton->setObjectName(QString::fromUtf8("oreButton"));
        oreButton->setGeometry(QRect(810, 80, 81, 31));
        sheepButton = new QPushButton(centralWidget);
        sheepButton->setObjectName(QString::fromUtf8("sheepButton"));
        sheepButton->setGeometry(QRect(810, 120, 81, 31));
        wheatButton = new QPushButton(centralWidget);
        wheatButton->setObjectName(QString::fromUtf8("wheatButton"));
        wheatButton->setGeometry(QRect(810, 160, 81, 31));
        woodButton = new QPushButton(centralWidget);
        woodButton->setObjectName(QString::fromUtf8("woodButton"));
        woodButton->setGeometry(QRect(810, 200, 81, 31));
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(770, 250, 101, 16));
        settlementButton = new QPushButton(centralWidget);
        settlementButton->setObjectName(QString::fromUtf8("settlementButton"));
        settlementButton->setGeometry(QRect(810, 270, 81, 31));
        cityButton = new QPushButton(centralWidget);
        cityButton->setObjectName(QString::fromUtf8("cityButton"));
        cityButton->setGeometry(QRect(810, 350, 81, 31));
        roadButton = new QPushButton(centralWidget);
        roadButton->setObjectName(QString::fromUtf8("roadButton"));
        roadButton->setGeometry(QRect(810, 310, 81, 31));
        tradeButton = new QPushButton(centralWidget);
        tradeButton->setObjectName(QString::fromUtf8("tradeButton"));
        tradeButton->setGeometry(QRect(670, 660, 121, 51));
        undoButton = new QPushButton(centralWidget);
        undoButton->setObjectName(QString::fromUtf8("undoButton"));
        undoButton->setGeometry(QRect(310, 660, 121, 51));
        developButton = new QPushButton(centralWidget);
        developButton->setObjectName(QString::fromUtf8("developButton"));
        developButton->setGeometry(QRect(800, 420, 121, 31));
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(770, 400, 131, 16));
        label_5 = new QLabel(centralWidget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(770, 530, 151, 16));
        KnightLabel = new QLabel(centralWidget);
        KnightLabel->setObjectName(QString::fromUtf8("KnightLabel"));
        KnightLabel->setGeometry(QRect(770, 550, 111, 16));
        brickLabel = new QLabel(centralWidget);
        brickLabel->setObjectName(QString::fromUtf8("brickLabel"));
        brickLabel->setEnabled(true);
        brickLabel->setGeometry(QRect(770, 50, 41, 16));
        oreLabel = new QLabel(centralWidget);
        oreLabel->setObjectName(QString::fromUtf8("oreLabel"));
        oreLabel->setGeometry(QRect(770, 90, 41, 16));
        sheepLabel = new QLabel(centralWidget);
        sheepLabel->setObjectName(QString::fromUtf8("sheepLabel"));
        sheepLabel->setGeometry(QRect(770, 130, 41, 16));
        wheatLabel = new QLabel(centralWidget);
        wheatLabel->setObjectName(QString::fromUtf8("wheatLabel"));
        wheatLabel->setGeometry(QRect(770, 170, 41, 16));
        woodLabel = new QLabel(centralWidget);
        woodLabel->setObjectName(QString::fromUtf8("woodLabel"));
        woodLabel->setGeometry(QRect(770, 210, 41, 16));
        label_6 = new QLabel(centralWidget);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(820, 0, 55, 16));
        settleLabel = new QLabel(centralWidget);
        settleLabel->setObjectName(QString::fromUtf8("settleLabel"));
        settleLabel->setGeometry(QRect(770, 280, 41, 21));
        roadLabel = new QLabel(centralWidget);
        roadLabel->setObjectName(QString::fromUtf8("roadLabel"));
        roadLabel->setGeometry(QRect(770, 320, 41, 21));
        cityLabel = new QLabel(centralWidget);
        cityLabel->setObjectName(QString::fromUtf8("cityLabel"));
        cityLabel->setGeometry(QRect(770, 360, 41, 21));
        developLabel = new QLabel(centralWidget);
        developLabel->setObjectName(QString::fromUtf8("developLabel"));
        developLabel->setGeometry(QRect(770, 430, 31, 21));
        Player4Button = new QPushButton(centralWidget);
        Player4Button->setObjectName(QString::fromUtf8("Player4Button"));
        Player4Button->setGeometry(QRect(670, 0, 91, 21));
        Player1Button = new QPushButton(centralWidget);
        Player1Button->setObjectName(QString::fromUtf8("Player1Button"));
        Player1Button->setGeometry(QRect(20, 0, 91, 21));
        Player3Button = new QPushButton(centralWidget);
        Player3Button->setObjectName(QString::fromUtf8("Player3Button"));
        Player3Button->setGeometry(QRect(670, 630, 91, 21));
        Player2Button = new QPushButton(centralWidget);
        Player2Button->setObjectName(QString::fromUtf8("Player2Button"));
        Player2Button->setGeometry(QRect(20, 630, 91, 21));
        label_7 = new QLabel(centralWidget);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(770, 590, 151, 16));
        RoadLabel = new QLabel(centralWidget);
        RoadLabel->setObjectName(QString::fromUtf8("RoadLabel"));
        RoadLabel->setGeometry(QRect(770, 610, 111, 16));
        label_8 = new QLabel(centralWidget);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(790, 510, 101, 20));
        tradeView = new QGraphicsView(centralWidget);
        tradeView->setObjectName(QString::fromUtf8("tradeView"));
        tradeView->setGeometry(QRect(140, 60, 501, 481));
        Player1Trade = new QLabel(centralWidget);
        Player1Trade->setObjectName(QString::fromUtf8("Player1Trade"));
        Player1Trade->setGeometry(QRect(200, 170, 55, 16));
        Player2Trade = new QLabel(centralWidget);
        Player2Trade->setObjectName(QString::fromUtf8("Player2Trade"));
        Player2Trade->setGeometry(QRect(550, 170, 55, 16));
        brickTrade = new QLabel(centralWidget);
        brickTrade->setObjectName(QString::fromUtf8("brickTrade"));
        brickTrade->setGeometry(QRect(200, 190, 55, 16));
        woodTrade = new QLabel(centralWidget);
        woodTrade->setObjectName(QString::fromUtf8("woodTrade"));
        woodTrade->setGeometry(QRect(200, 270, 61, 16));
        oreTrade = new QLabel(centralWidget);
        oreTrade->setObjectName(QString::fromUtf8("oreTrade"));
        oreTrade->setGeometry(QRect(200, 210, 55, 16));
        sheepTrade = new QLabel(centralWidget);
        sheepTrade->setObjectName(QString::fromUtf8("sheepTrade"));
        sheepTrade->setGeometry(QRect(200, 230, 61, 16));
        wheatTrade = new QLabel(centralWidget);
        wheatTrade->setObjectName(QString::fromUtf8("wheatTrade"));
        wheatTrade->setGeometry(QRect(200, 250, 61, 16));
        brick2Trade = new QLabel(centralWidget);
        brick2Trade->setObjectName(QString::fromUtf8("brick2Trade"));
        brick2Trade->setGeometry(QRect(550, 190, 55, 16));
        ore2Trade = new QLabel(centralWidget);
        ore2Trade->setObjectName(QString::fromUtf8("ore2Trade"));
        ore2Trade->setGeometry(QRect(550, 210, 55, 16));
        wheat2Trade = new QLabel(centralWidget);
        wheat2Trade->setObjectName(QString::fromUtf8("wheat2Trade"));
        wheat2Trade->setGeometry(QRect(550, 250, 61, 16));
        sheep2Trade = new QLabel(centralWidget);
        sheep2Trade->setObjectName(QString::fromUtf8("sheep2Trade"));
        sheep2Trade->setGeometry(QRect(550, 230, 61, 16));
        wood2Trade = new QLabel(centralWidget);
        wood2Trade->setObjectName(QString::fromUtf8("wood2Trade"));
        wood2Trade->setGeometry(QRect(550, 270, 61, 16));
        oreIn = new QLineEdit(centralWidget);
        oreIn->setObjectName(QString::fromUtf8("oreIn"));
        oreIn->setGeometry(QRect(310, 210, 61, 22));
        brickIn = new QLineEdit(centralWidget);
        brickIn->setObjectName(QString::fromUtf8("brickIn"));
        brickIn->setGeometry(QRect(310, 190, 61, 22));
        sheepIn = new QLineEdit(centralWidget);
        sheepIn->setObjectName(QString::fromUtf8("sheepIn"));
        sheepIn->setGeometry(QRect(310, 230, 61, 22));
        wheatIn = new QLineEdit(centralWidget);
        wheatIn->setObjectName(QString::fromUtf8("wheatIn"));
        wheatIn->setGeometry(QRect(310, 250, 61, 22));
        woodIn = new QLineEdit(centralWidget);
        woodIn->setObjectName(QString::fromUtf8("woodIn"));
        woodIn->setGeometry(QRect(310, 270, 61, 22));
        woodOut = new QLineEdit(centralWidget);
        woodOut->setObjectName(QString::fromUtf8("woodOut"));
        woodOut->setGeometry(QRect(420, 270, 61, 22));
        oreOut = new QLineEdit(centralWidget);
        oreOut->setObjectName(QString::fromUtf8("oreOut"));
        oreOut->setGeometry(QRect(420, 210, 61, 22));
        wheatOut = new QLineEdit(centralWidget);
        wheatOut->setObjectName(QString::fromUtf8("wheatOut"));
        wheatOut->setGeometry(QRect(420, 250, 61, 22));
        sheepOut = new QLineEdit(centralWidget);
        sheepOut->setObjectName(QString::fromUtf8("sheepOut"));
        sheepOut->setGeometry(QRect(420, 230, 61, 22));
        brickOut = new QLineEdit(centralWidget);
        brickOut->setObjectName(QString::fromUtf8("brickOut"));
        brickOut->setGeometry(QRect(420, 190, 61, 22));
        forLabel = new QLabel(centralWidget);
        forLabel->setObjectName(QString::fromUtf8("forLabel"));
        forLabel->setGeometry(QRect(380, 230, 21, 16));
        acceptButton = new QPushButton(centralWidget);
        acceptButton->setObjectName(QString::fromUtf8("acceptButton"));
        acceptButton->setGeometry(QRect(340, 330, 121, 31));
        denyButton = new QPushButton(centralWidget);
        denyButton->setObjectName(QString::fromUtf8("denyButton"));
        denyButton->setGeometry(QRect(340, 370, 121, 31));
        GameWindow->setCentralWidget(centralWidget);
        mainToolBar = new QToolBar(GameWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        GameWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(GameWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        GameWindow->setStatusBar(statusBar);

        retranslateUi(GameWindow);

        findOrderButton->setDefault(false);


        QMetaObject::connectSlotsByName(GameWindow);
    } // setupUi

    void retranslateUi(QMainWindow *GameWindow)
    {
        GameWindow->setWindowTitle(QCoreApplication::translate("GameWindow", "PlotWindow", nullptr));
        endTurnButton->setText(QCoreApplication::translate("GameWindow", "End Turn", nullptr));
        buildButton->setText(QCoreApplication::translate("GameWindow", "Build", nullptr));
        Wood1->setText(QCoreApplication::translate("GameWindow", "Wood: 0", nullptr));
        Ore1->setText(QCoreApplication::translate("GameWindow", "Ore: 0", nullptr));
        Sheep1->setText(QCoreApplication::translate("GameWindow", "Sheep: 0", nullptr));
        Brick1->setText(QCoreApplication::translate("GameWindow", "Brick: 0", nullptr));
        Wheat1->setText(QCoreApplication::translate("GameWindow", "Wheat: 0", nullptr));
        Brick2->setText(QCoreApplication::translate("GameWindow", "Brick: 0", nullptr));
        Wood2->setText(QCoreApplication::translate("GameWindow", "Wood: 0", nullptr));
        Wheat2->setText(QCoreApplication::translate("GameWindow", "Wheat: 0", nullptr));
        Ore2->setText(QCoreApplication::translate("GameWindow", "Ore: 0", nullptr));
        Sheep2->setText(QCoreApplication::translate("GameWindow", "Sheep: 0", nullptr));
        Brick3->setText(QCoreApplication::translate("GameWindow", "Brick: 0", nullptr));
        Sheep3->setText(QCoreApplication::translate("GameWindow", "Sheep: 0", nullptr));
        Wheat3->setText(QCoreApplication::translate("GameWindow", "Wheat: 0", nullptr));
        Ore3->setText(QCoreApplication::translate("GameWindow", "Ore: 0", nullptr));
        Wood3->setText(QCoreApplication::translate("GameWindow", "Wood: 0", nullptr));
        Ore4->setText(QCoreApplication::translate("GameWindow", "Ore: 0", nullptr));
        Sheep4->setText(QCoreApplication::translate("GameWindow", "Sheep: 0", nullptr));
        Wheat4->setText(QCoreApplication::translate("GameWindow", "Wheat: 0", nullptr));
        Wood4->setText(QCoreApplication::translate("GameWindow", "Wood: 0", nullptr));
        Brick4->setText(QCoreApplication::translate("GameWindow", "Brick: 0", nullptr));
        findOrderButton->setText(QCoreApplication::translate("GameWindow", "Enter Number of Players", nullptr));
        label->setText(QCoreApplication::translate("GameWindow", "Enter Number of Players:", nullptr));
        TextBox->setText(QString());
        p1d1->setText(QString());
        p1d2->setText(QString());
        p4d1->setText(QString());
        p4d2->setText(QString());
        p3d1->setText(QString());
        p3d2->setText(QString());
        p2d2->setText(QString());
        p2d1->setText(QString());
        label_2->setText(QCoreApplication::translate("GameWindow", "Resources:", nullptr));
        brickButton->setText(QCoreApplication::translate("GameWindow", "Brick", nullptr));
        oreButton->setText(QCoreApplication::translate("GameWindow", "Ore", nullptr));
        sheepButton->setText(QCoreApplication::translate("GameWindow", "Sheep", nullptr));
        wheatButton->setText(QCoreApplication::translate("GameWindow", "Wheat", nullptr));
        woodButton->setText(QCoreApplication::translate("GameWindow", "Wood", nullptr));
        label_3->setText(QCoreApplication::translate("GameWindow", "Building options:", nullptr));
        settlementButton->setText(QCoreApplication::translate("GameWindow", "Settlement", nullptr));
        cityButton->setText(QCoreApplication::translate("GameWindow", "City", nullptr));
        roadButton->setText(QCoreApplication::translate("GameWindow", "Road", nullptr));
        tradeButton->setText(QCoreApplication::translate("GameWindow", "Trade", nullptr));
        undoButton->setText(QCoreApplication::translate("GameWindow", "Undo", nullptr));
        developButton->setText(QCoreApplication::translate("GameWindow", "Development Card", nullptr));
        label_4->setText(QCoreApplication::translate("GameWindow", "Purchase and use a:", nullptr));
        label_5->setText(QCoreApplication::translate("GameWindow", "Player with most Knights:", nullptr));
        KnightLabel->setText(QCoreApplication::translate("GameWindow", "No one has 3+", nullptr));
        brickLabel->setText(QCoreApplication::translate("GameWindow", "19", nullptr));
        oreLabel->setText(QCoreApplication::translate("GameWindow", "19", nullptr));
        sheepLabel->setText(QCoreApplication::translate("GameWindow", "19", nullptr));
        wheatLabel->setText(QCoreApplication::translate("GameWindow", "19", nullptr));
        woodLabel->setText(QCoreApplication::translate("GameWindow", "19", nullptr));
        label_6->setText(QCoreApplication::translate("GameWindow", "Bank", nullptr));
        settleLabel->setText(QCoreApplication::translate("GameWindow", "5", nullptr));
        roadLabel->setText(QCoreApplication::translate("GameWindow", "15", nullptr));
        cityLabel->setText(QCoreApplication::translate("GameWindow", "4", nullptr));
        developLabel->setText(QCoreApplication::translate("GameWindow", "25", nullptr));
        Player4Button->setText(QCoreApplication::translate("GameWindow", "Player4 VP: 0", nullptr));
        Player1Button->setText(QCoreApplication::translate("GameWindow", "Player1 VP: 0", nullptr));
        Player3Button->setText(QCoreApplication::translate("GameWindow", "Player3 VP: 0", nullptr));
        Player2Button->setText(QCoreApplication::translate("GameWindow", "Player2 VP: 0", nullptr));
        label_7->setText(QCoreApplication::translate("GameWindow", "Player with most Roads:", nullptr));
        RoadLabel->setText(QCoreApplication::translate("GameWindow", "No one has 5+", nullptr));
        label_8->setText(QCoreApplication::translate("GameWindow", "+2 Vp conditions", nullptr));
        Player1Trade->setText(QCoreApplication::translate("GameWindow", "Player 1:", nullptr));
        Player2Trade->setText(QCoreApplication::translate("GameWindow", "Player 2:", nullptr));
        brickTrade->setText(QCoreApplication::translate("GameWindow", "Brick: 0", nullptr));
        woodTrade->setText(QCoreApplication::translate("GameWindow", "Wood: 0", nullptr));
        oreTrade->setText(QCoreApplication::translate("GameWindow", "Ore: 0", nullptr));
        sheepTrade->setText(QCoreApplication::translate("GameWindow", "Sheep: 0", nullptr));
        wheatTrade->setText(QCoreApplication::translate("GameWindow", "Wheat: 0", nullptr));
        brick2Trade->setText(QCoreApplication::translate("GameWindow", "Brick: 0", nullptr));
        ore2Trade->setText(QCoreApplication::translate("GameWindow", "Ore: 0", nullptr));
        wheat2Trade->setText(QCoreApplication::translate("GameWindow", "Wheat: 0", nullptr));
        sheep2Trade->setText(QCoreApplication::translate("GameWindow", "Sheep: 0", nullptr));
        wood2Trade->setText(QCoreApplication::translate("GameWindow", "Wood: 0", nullptr));
        forLabel->setText(QCoreApplication::translate("GameWindow", "for", nullptr));
        acceptButton->setText(QCoreApplication::translate("GameWindow", "Accept", nullptr));
        denyButton->setText(QCoreApplication::translate("GameWindow", "Deny", nullptr));
    } // retranslateUi

};

namespace Ui {
    class GameWindow: public Ui_GameWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_GAMEWINDOW_H
