function TraceInfoFlag() {
    this.traceFlag = new Array();
    this.traceFlag["px4demo_top_model_pil.cpp:66c7"]=1;
    this.traceFlag["px4demo_top_model_pil.cpp:72c24"]=1;
    this.traceFlag["px4demo_top_model_pil.cpp:115c7"]=1;
    this.traceFlag["px4demo_top_model_pil.cpp:131c15"]=1;
    this.traceFlag["px4demo_top_model_pil.cpp:131c34"]=1;
    this.traceFlag["px4demo_top_model_pil.cpp:142c31"]=1;
}
top.TraceInfoFlag.instance = new TraceInfoFlag();
function TraceInfoLineFlag() {
    this.lineTraceFlag = new Array();
    this.lineTraceFlag["px4demo_top_model_pil.cpp:25"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.cpp:26"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.cpp:45"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.cpp:54"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.cpp:61"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.cpp:62"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.cpp:65"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.cpp:66"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.cpp:72"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.cpp:77"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.cpp:93"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.cpp:102"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.cpp:110"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.cpp:111"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.cpp:114"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.cpp:115"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.cpp:131"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.cpp:134"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.cpp:142"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.cpp:145"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.cpp:154"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.cpp:159"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.h:40"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.h:41"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.h:42"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.h:43"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.h:48"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.h:49"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.h:54"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.h:57"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.h:60"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.h:63"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.h:67"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.h:70"]=1;
    this.lineTraceFlag["px4demo_top_model_pil.h:73"]=1;
}
top.TraceInfoLineFlag.instance = new TraceInfoLineFlag();
